# Generated by Django 4.0.3 on 2022-04-05 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_region', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cand', models.CharField(max_length=250)),
                ('apellido_cand', models.CharField(max_length=250)),
                ('edad', models.IntegerField(default=22)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.region')),
                ('ocupacion', models.CharField(max_length=200)),
            ],
        ),
    ]
